apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubernetes-simple-app
  name: kubernetes-simple-app-svc
  namespace: default
spec:
  ports:
  - nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kubernetes-simple-app
  type: NodePort